[2025-02-11T05:16:22.789+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2025-02-10T00:00:00+00:00 [queued]>
[2025-02-11T05:16:22.806+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2025-02-10T00:00:00+00:00 [queued]>
[2025-02-11T05:16:22.807+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-02-11T05:16:22.808+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-02-11T05:16:22.809+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-02-11T05:16:22.840+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-02-10 00:00:00+00:00
[2025-02-11T05:16:22.850+0000] {standard_task_runner.py:55} INFO - Started process 82 to run task
[2025-02-11T05:16:22.856+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2025-02-10T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpo0mr8e6c']
[2025-02-11T05:16:22.860+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask is_api_available
[2025-02-11T05:16:22.983+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2025-02-10T00:00:00+00:00 [running]> on host 697030c1eb04
[2025-02-11T05:16:23.111+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2025-02-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-02-10T00:00:00+00:00
[2025-02-11T05:16:23.112+0000] {http.py:120} INFO - Poking: api/
[2025-02-11T05:16:23.127+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2025-02-11T05:16:23.129+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2025-02-11T05:16:23.477+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2025-02-11T05:16:23.505+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20250210T000000, start_date=20250211T051622, end_date=20250211T051623
[2025-02-11T05:16:23.569+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-02-11T05:16:23.647+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
