[2025-02-11T05:16:20.822+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2025-02-09T00:00:00+00:00 [queued]>
[2025-02-11T05:16:20.849+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2025-02-09T00:00:00+00:00 [queued]>
[2025-02-11T05:16:20.850+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-02-11T05:16:20.851+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-02-11T05:16:20.851+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-02-11T05:16:20.886+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2025-02-09 00:00:00+00:00
[2025-02-11T05:16:20.902+0000] {standard_task_runner.py:55} INFO - Started process 76 to run task
[2025-02-11T05:16:20.914+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2025-02-09T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpabd1u7if']
[2025-02-11T05:16:20.922+0000] {standard_task_runner.py:83} INFO - Job 42: Subtask create_table
[2025-02-11T05:16:21.089+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table scheduled__2025-02-09T00:00:00+00:00 [running]> on host 697030c1eb04
[2025-02-11T05:16:21.247+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2025-02-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-02-09T00:00:00+00:00
[2025-02-11T05:16:21.266+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2025-02-11T05:16:21.272+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
                );
            , parameters: None
[2025-02-11T05:16:21.275+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2025-02-11T05:16:21.294+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20250209T000000, start_date=20250211T051620, end_date=20250211T051621
[2025-02-11T05:16:21.348+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-02-11T05:16:21.555+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
